# Generated by Django 4.2.4 on 2023-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_source',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
