# Generated by Django 4.2.4 on 2023-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_news_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popularity_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
            preserve_default=False,
        ),
    ]
