# Generated by Django 4.2.4 on 2023-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_news_popularity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='popularity_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
